//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WBS_WEB.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MasterList> MasterList
        {
            get
            {
                if ((_MasterList == null))
                {
                    _MasterList = base.CreateObjectSet<MasterList>("MasterList");
                }
                return _MasterList;
            }
        }
        private ObjectSet<MasterList> _MasterList;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MasterList EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMasterList(MasterList masterList)
        {
            base.AddObject("MasterList", masterList);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="MasterList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MasterList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MasterList object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="sSMA_TimeStamp">Initial value of the SSMA_TimeStamp property.</param>
        public static MasterList CreateMasterList(global::System.Int32 id, global::System.Byte[] sSMA_TimeStamp)
        {
            MasterList masterList = new MasterList();
            masterList.ID = id;
            masterList.SSMA_TimeStamp = sSMA_TimeStamp;
            return masterList;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TASK_ID
        {
            get
            {
                return _TASK_ID;
            }
            set
            {
                OnTASK_IDChanging(value);
                ReportPropertyChanging("TASK_ID");
                _TASK_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TASK_ID");
                OnTASK_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _TASK_ID;
        partial void OnTASK_IDChanging(Nullable<global::System.Int32> value);
        partial void OnTASK_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME_JP
        {
            get
            {
                return _NAME_JP;
            }
            set
            {
                OnNAME_JPChanging(value);
                ReportPropertyChanging("NAME_JP");
                _NAME_JP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME_JP");
                OnNAME_JPChanged();
            }
        }
        private global::System.String _NAME_JP;
        partial void OnNAME_JPChanging(global::System.String value);
        partial void OnNAME_JPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RECV_DATE
        {
            get
            {
                return _RECV_DATE;
            }
            set
            {
                OnRECV_DATEChanging(value);
                ReportPropertyChanging("RECV_DATE");
                _RECV_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RECV_DATE");
                OnRECV_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _RECV_DATE;
        partial void OnRECV_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnRECV_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IS_PLANED
        {
            get
            {
                return _IS_PLANED;
            }
            set
            {
                OnIS_PLANEDChanging(value);
                ReportPropertyChanging("IS_PLANED");
                _IS_PLANED = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IS_PLANED");
                OnIS_PLANEDChanged();
            }
        }
        private global::System.String _IS_PLANED;
        partial void OnIS_PLANEDChanging(global::System.String value);
        partial void OnIS_PLANEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REQ_FROM
        {
            get
            {
                return _REQ_FROM;
            }
            set
            {
                OnREQ_FROMChanging(value);
                ReportPropertyChanging("REQ_FROM");
                _REQ_FROM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REQ_FROM");
                OnREQ_FROMChanged();
            }
        }
        private global::System.String _REQ_FROM;
        partial void OnREQ_FROMChanging(global::System.String value);
        partial void OnREQ_FROMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RANK
        {
            get
            {
                return _RANK;
            }
            set
            {
                OnRANKChanging(value);
                ReportPropertyChanging("RANK");
                _RANK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RANK");
                OnRANKChanged();
            }
        }
        private global::System.String _RANK;
        partial void OnRANKChanging(global::System.String value);
        partial void OnRANKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TASK_TYPE
        {
            get
            {
                return _TASK_TYPE;
            }
            set
            {
                OnTASK_TYPEChanging(value);
                ReportPropertyChanging("TASK_TYPE");
                _TASK_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TASK_TYPE");
                OnTASK_TYPEChanged();
            }
        }
        private global::System.String _TASK_TYPE;
        partial void OnTASK_TYPEChanging(global::System.String value);
        partial void OnTASK_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PIC
        {
            get
            {
                return _PIC;
            }
            set
            {
                OnPICChanging(value);
                ReportPropertyChanging("PIC");
                _PIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PIC");
                OnPICChanged();
            }
        }
        private global::System.String _PIC;
        partial void OnPICChanging(global::System.String value);
        partial void OnPICChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PIC_JP
        {
            get
            {
                return _PIC_JP;
            }
            set
            {
                OnPIC_JPChanging(value);
                ReportPropertyChanging("PIC_JP");
                _PIC_JP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PIC_JP");
                OnPIC_JPChanged();
            }
        }
        private global::System.String _PIC_JP;
        partial void OnPIC_JPChanging(global::System.String value);
        partial void OnPIC_JPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VN_OR_JP
        {
            get
            {
                return _VN_OR_JP;
            }
            set
            {
                OnVN_OR_JPChanging(value);
                ReportPropertyChanging("VN_OR_JP");
                _VN_OR_JP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VN_OR_JP");
                OnVN_OR_JPChanged();
            }
        }
        private global::System.String _VN_OR_JP;
        partial void OnVN_OR_JPChanging(global::System.String value);
        partial void OnVN_OR_JPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CTRL
        {
            get
            {
                return _CTRL;
            }
            set
            {
                OnCTRLChanging(value);
                ReportPropertyChanging("CTRL");
                _CTRL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CTRL");
                OnCTRLChanged();
            }
        }
        private global::System.String _CTRL;
        partial void OnCTRLChanging(global::System.String value);
        partial void OnCTRLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ASSIGN_DATE
        {
            get
            {
                return _ASSIGN_DATE;
            }
            set
            {
                OnASSIGN_DATEChanging(value);
                ReportPropertyChanging("ASSIGN_DATE");
                _ASSIGN_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ASSIGN_DATE");
                OnASSIGN_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _ASSIGN_DATE;
        partial void OnASSIGN_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnASSIGN_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DESIRED_REL_DATE
        {
            get
            {
                return _DESIRED_REL_DATE;
            }
            set
            {
                OnDESIRED_REL_DATEChanging(value);
                ReportPropertyChanging("DESIRED_REL_DATE");
                _DESIRED_REL_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DESIRED_REL_DATE");
                OnDESIRED_REL_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _DESIRED_REL_DATE;
        partial void OnDESIRED_REL_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnDESIRED_REL_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ABS_REL_DATE
        {
            get
            {
                return _ABS_REL_DATE;
            }
            set
            {
                OnABS_REL_DATEChanging(value);
                ReportPropertyChanging("ABS_REL_DATE");
                _ABS_REL_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ABS_REL_DATE");
                OnABS_REL_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _ABS_REL_DATE;
        partial void OnABS_REL_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnABS_REL_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EFFORT_PLAN_JP
        {
            get
            {
                return _EFFORT_PLAN_JP;
            }
            set
            {
                OnEFFORT_PLAN_JPChanging(value);
                ReportPropertyChanging("EFFORT_PLAN_JP");
                _EFFORT_PLAN_JP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EFFORT_PLAN_JP");
                OnEFFORT_PLAN_JPChanged();
            }
        }
        private global::System.String _EFFORT_PLAN_JP;
        partial void OnEFFORT_PLAN_JPChanging(global::System.String value);
        partial void OnEFFORT_PLAN_JPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EFFORT_ACTUAL_JP
        {
            get
            {
                return _EFFORT_ACTUAL_JP;
            }
            set
            {
                OnEFFORT_ACTUAL_JPChanging(value);
                ReportPropertyChanging("EFFORT_ACTUAL_JP");
                _EFFORT_ACTUAL_JP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EFFORT_ACTUAL_JP");
                OnEFFORT_ACTUAL_JPChanged();
            }
        }
        private global::System.String _EFFORT_ACTUAL_JP;
        partial void OnEFFORT_ACTUAL_JPChanging(global::System.String value);
        partial void OnEFFORT_ACTUAL_JPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EFFORT_PLAN
        {
            get
            {
                return _EFFORT_PLAN;
            }
            set
            {
                OnEFFORT_PLANChanging(value);
                ReportPropertyChanging("EFFORT_PLAN");
                _EFFORT_PLAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EFFORT_PLAN");
                OnEFFORT_PLANChanged();
            }
        }
        private global::System.String _EFFORT_PLAN;
        partial void OnEFFORT_PLANChanging(global::System.String value);
        partial void OnEFFORT_PLANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EFFORT_ACTUAL
        {
            get
            {
                return _EFFORT_ACTUAL;
            }
            set
            {
                OnEFFORT_ACTUALChanging(value);
                ReportPropertyChanging("EFFORT_ACTUAL");
                _EFFORT_ACTUAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EFFORT_ACTUAL");
                OnEFFORT_ACTUALChanged();
            }
        }
        private global::System.String _EFFORT_ACTUAL;
        partial void OnEFFORT_ACTUALChanging(global::System.String value);
        partial void OnEFFORT_ACTUALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IS_TEMP_ANS
        {
            get
            {
                return _IS_TEMP_ANS;
            }
            set
            {
                OnIS_TEMP_ANSChanging(value);
                ReportPropertyChanging("IS_TEMP_ANS");
                _IS_TEMP_ANS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IS_TEMP_ANS");
                OnIS_TEMP_ANSChanged();
            }
        }
        private global::System.String _IS_TEMP_ANS;
        partial void OnIS_TEMP_ANSChanging(global::System.String value);
        partial void OnIS_TEMP_ANSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WHY_NOT_VN
        {
            get
            {
                return _WHY_NOT_VN;
            }
            set
            {
                OnWHY_NOT_VNChanging(value);
                ReportPropertyChanging("WHY_NOT_VN");
                _WHY_NOT_VN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WHY_NOT_VN");
                OnWHY_NOT_VNChanged();
            }
        }
        private global::System.String _WHY_NOT_VN;
        partial void OnWHY_NOT_VNChanging(global::System.String value);
        partial void OnWHY_NOT_VNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HELP_DESK
        {
            get
            {
                return _HELP_DESK;
            }
            set
            {
                OnHELP_DESKChanging(value);
                ReportPropertyChanging("HELP_DESK");
                _HELP_DESK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HELP_DESK");
                OnHELP_DESKChanged();
            }
        }
        private global::System.String _HELP_DESK;
        partial void OnHELP_DESKChanging(global::System.String value);
        partial void OnHELP_DESKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STATUS
        {
            get
            {
                return _STATUS;
            }
            set
            {
                OnSTATUSChanging(value);
                ReportPropertyChanging("STATUS");
                _STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STATUS");
                OnSTATUSChanged();
            }
        }
        private global::System.String _STATUS;
        partial void OnSTATUSChanging(global::System.String value);
        partial void OnSTATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COUNT_ANS
        {
            get
            {
                return _COUNT_ANS;
            }
            set
            {
                OnCOUNT_ANSChanging(value);
                ReportPropertyChanging("COUNT_ANS");
                _COUNT_ANS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COUNT_ANS");
                OnCOUNT_ANSChanged();
            }
        }
        private global::System.String _COUNT_ANS;
        partial void OnCOUNT_ANSChanging(global::System.String value);
        partial void OnCOUNT_ANSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LAST_CONTACT_TIME
        {
            get
            {
                return _LAST_CONTACT_TIME;
            }
            set
            {
                OnLAST_CONTACT_TIMEChanging(value);
                ReportPropertyChanging("LAST_CONTACT_TIME");
                _LAST_CONTACT_TIME = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LAST_CONTACT_TIME");
                OnLAST_CONTACT_TIMEChanged();
            }
        }
        private Nullable<global::System.DateTime> _LAST_CONTACT_TIME;
        partial void OnLAST_CONTACT_TIMEChanging(Nullable<global::System.DateTime> value);
        partial void OnLAST_CONTACT_TIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COUNT_FROM_LAST_CONTACT
        {
            get
            {
                return _COUNT_FROM_LAST_CONTACT;
            }
            set
            {
                OnCOUNT_FROM_LAST_CONTACTChanging(value);
                ReportPropertyChanging("COUNT_FROM_LAST_CONTACT");
                _COUNT_FROM_LAST_CONTACT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COUNT_FROM_LAST_CONTACT");
                OnCOUNT_FROM_LAST_CONTACTChanged();
            }
        }
        private global::System.String _COUNT_FROM_LAST_CONTACT;
        partial void OnCOUNT_FROM_LAST_CONTACTChanging(global::System.String value);
        partial void OnCOUNT_FROM_LAST_CONTACTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REQ_DEPT
        {
            get
            {
                return _REQ_DEPT;
            }
            set
            {
                OnREQ_DEPTChanging(value);
                ReportPropertyChanging("REQ_DEPT");
                _REQ_DEPT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REQ_DEPT");
                OnREQ_DEPTChanged();
            }
        }
        private global::System.String _REQ_DEPT;
        partial void OnREQ_DEPTChanging(global::System.String value);
        partial void OnREQ_DEPTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> REL_PLAN
        {
            get
            {
                return _REL_PLAN;
            }
            set
            {
                OnREL_PLANChanging(value);
                ReportPropertyChanging("REL_PLAN");
                _REL_PLAN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("REL_PLAN");
                OnREL_PLANChanged();
            }
        }
        private Nullable<global::System.DateTime> _REL_PLAN;
        partial void OnREL_PLANChanging(Nullable<global::System.DateTime> value);
        partial void OnREL_PLANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OLD_REL_PLAN
        {
            get
            {
                return _OLD_REL_PLAN;
            }
            set
            {
                OnOLD_REL_PLANChanging(value);
                ReportPropertyChanging("OLD_REL_PLAN");
                _OLD_REL_PLAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OLD_REL_PLAN");
                OnOLD_REL_PLANChanged();
            }
        }
        private global::System.String _OLD_REL_PLAN;
        partial void OnOLD_REL_PLANChanging(global::System.String value);
        partial void OnOLD_REL_PLANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FIN_DATE
        {
            get
            {
                return _FIN_DATE;
            }
            set
            {
                OnFIN_DATEChanging(value);
                ReportPropertyChanging("FIN_DATE");
                _FIN_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FIN_DATE");
                OnFIN_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _FIN_DATE;
        partial void OnFIN_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnFIN_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LEAD_TIME
        {
            get
            {
                return _LEAD_TIME;
            }
            set
            {
                OnLEAD_TIMEChanging(value);
                ReportPropertyChanging("LEAD_TIME");
                _LEAD_TIME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LEAD_TIME");
                OnLEAD_TIMEChanged();
            }
        }
        private global::System.String _LEAD_TIME;
        partial void OnLEAD_TIMEChanging(global::System.String value);
        partial void OnLEAD_TIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REMARK
        {
            get
            {
                return _REMARK;
            }
            set
            {
                OnREMARKChanging(value);
                ReportPropertyChanging("REMARK");
                _REMARK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REMARK");
                OnREMARKChanged();
            }
        }
        private global::System.String _REMARK;
        partial void OnREMARKChanging(global::System.String value);
        partial void OnREMARKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME_VN
        {
            get
            {
                return _NAME_VN;
            }
            set
            {
                OnNAME_VNChanging(value);
                ReportPropertyChanging("NAME_VN");
                _NAME_VN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME_VN");
                OnNAME_VNChanged();
            }
        }
        private global::System.String _NAME_VN;
        partial void OnNAME_VNChanging(global::System.String value);
        partial void OnNAME_VNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KEYWORD
        {
            get
            {
                return _KEYWORD;
            }
            set
            {
                OnKEYWORDChanging(value);
                ReportPropertyChanging("KEYWORD");
                _KEYWORD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KEYWORD");
                OnKEYWORDChanged();
            }
        }
        private global::System.String _KEYWORD;
        partial void OnKEYWORDChanging(global::System.String value);
        partial void OnKEYWORDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUGGEST
        {
            get
            {
                return _SUGGEST;
            }
            set
            {
                OnSUGGESTChanging(value);
                ReportPropertyChanging("SUGGEST");
                _SUGGEST = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUGGEST");
                OnSUGGESTChanged();
            }
        }
        private global::System.String _SUGGEST;
        partial void OnSUGGESTChanging(global::System.String value);
        partial void OnSUGGESTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WIKI_JP_LINK
        {
            get
            {
                return _WIKI_JP_LINK;
            }
            set
            {
                OnWIKI_JP_LINKChanging(value);
                ReportPropertyChanging("WIKI_JP_LINK");
                _WIKI_JP_LINK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WIKI_JP_LINK");
                OnWIKI_JP_LINKChanged();
            }
        }
        private global::System.String _WIKI_JP_LINK;
        partial void OnWIKI_JP_LINKChanging(global::System.String value);
        partial void OnWIKI_JP_LINKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PLAN_EXSE
        {
            get
            {
                return _PLAN_EXSE;
            }
            set
            {
                OnPLAN_EXSEChanging(value);
                ReportPropertyChanging("PLAN_EXSE");
                _PLAN_EXSE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PLAN_EXSE");
                OnPLAN_EXSEChanged();
            }
        }
        private global::System.String _PLAN_EXSE;
        partial void OnPLAN_EXSEChanging(global::System.String value);
        partial void OnPLAN_EXSEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PLAN_COM
        {
            get
            {
                return _PLAN_COM;
            }
            set
            {
                OnPLAN_COMChanging(value);
                ReportPropertyChanging("PLAN_COM");
                _PLAN_COM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PLAN_COM");
                OnPLAN_COMChanged();
            }
        }
        private global::System.String _PLAN_COM;
        partial void OnPLAN_COMChanging(global::System.String value);
        partial void OnPLAN_COMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACTUAL_EXSE
        {
            get
            {
                return _ACTUAL_EXSE;
            }
            set
            {
                OnACTUAL_EXSEChanging(value);
                ReportPropertyChanging("ACTUAL_EXSE");
                _ACTUAL_EXSE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACTUAL_EXSE");
                OnACTUAL_EXSEChanged();
            }
        }
        private global::System.String _ACTUAL_EXSE;
        partial void OnACTUAL_EXSEChanging(global::System.String value);
        partial void OnACTUAL_EXSEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACTUAL_COM
        {
            get
            {
                return _ACTUAL_COM;
            }
            set
            {
                OnACTUAL_COMChanging(value);
                ReportPropertyChanging("ACTUAL_COM");
                _ACTUAL_COM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACTUAL_COM");
                OnACTUAL_COMChanged();
            }
        }
        private global::System.String _ACTUAL_COM;
        partial void OnACTUAL_COMChanging(global::System.String value);
        partial void OnACTUAL_COMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UPDATE_STAMP
        {
            get
            {
                return _UPDATE_STAMP;
            }
            set
            {
                OnUPDATE_STAMPChanging(value);
                ReportPropertyChanging("UPDATE_STAMP");
                _UPDATE_STAMP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UPDATE_STAMP");
                OnUPDATE_STAMPChanged();
            }
        }
        private Nullable<global::System.DateTime> _UPDATE_STAMP;
        partial void OnUPDATE_STAMPChanging(Nullable<global::System.DateTime> value);
        partial void OnUPDATE_STAMPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] SSMA_TimeStamp
        {
            get
            {
                return StructuralObject.GetValidValue(_SSMA_TimeStamp);
            }
            set
            {
                OnSSMA_TimeStampChanging(value);
                ReportPropertyChanging("SSMA_TimeStamp");
                _SSMA_TimeStamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SSMA_TimeStamp");
                OnSSMA_TimeStampChanged();
            }
        }
        private global::System.Byte[] _SSMA_TimeStamp;
        partial void OnSSMA_TimeStampChanging(global::System.Byte[] value);
        partial void OnSSMA_TimeStampChanged();

        #endregion
    
    }

    #endregion
    
}
